sanatize inputs for ;

diff --git a/shttr/lib/io b/shttr/lib/io
--- a/shttr/lib/io
+++ b/shttr/lib/io
@@ -46,7 +46,12 @@ url_string_decode() {
 }
 
 verify_input() {
-  if [ -z $(echo "$1" | grep "=") ]; then
+  if echo "$1" | grep -v "="; then
+    echo "error"
+    exit 1
+  fi
+
+  if echo "$1" | grep ";"; then
     echo "error"
     exit 1
   fi
